### Create a Parcel
POST http://localhost:3000/admin/parcels
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNjRlMDhlZS1hMzgyLTRlOTEtYWYxZC1kYjVhYTJmNGZhNzIiLCJlbWFpbCI6ImpvbmF0aGFubXVsaW5nZW13YW5kaUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTM4MjMwNDksImV4cCI6MTc1MzkwOTQ0OX0.s1VbnuWsf4q25yJqPDW-Ir2KOmjus8XlXtJ6phjBiok

{
  "title": "Monitor Screen Delivery",
  "description": "Dell Latitude Screen",
  "weightKg": 0.5,
  "pickupAddress": "Uni Ndagani Street, Chuka",
  "destination": "Ndagani CBD",
  "senderName": "Jonathan M",
  "senderEmail": "jonathanmwandi@gmail.com",
  "receiverName": "Sam K",
  "receiverEmail": "jonathanmwandi6@gmail.com"
}

### Get all parcels
GET http://localhost:3000/admin/parcels
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNjRlMDhlZS1hMzgyLTRlOTEtYWYxZC1kYjVhYTJmNGZhNzIiLCJlbWFpbCI6ImpvbmF0aGFubXVsaW5nZW13YW5kaUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTI4NjIzOTgsImV4cCI6MTc1Mjk0ODc5OH0.F9XtLPS79r_N7AhcXi0_mq_F0d6wyakqD1qAvYJm9Uk


### Update a parcel's details
PATCH http://localhost:3000/admin/parcels/REPLACE_PARCEL_ID
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNjRlMDhlZS1hMzgyLTRlOTEtYWYxZC1kYjVhYTJmNGZhNzIiLCJlbWFpbCI6ImpvbmF0aGFubXVsaW5nZW13YW5kaUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTI0NDczMTEsImV4cCI6MTc1MjUzMzcxMX0.yrCWtZX7ZqM6B7moRFItvRG02RgcALZDksWWZt3oj-s


{
  "title": "Updated Parcel Title",
  "weightKg": 3.2,
  "description": "Updated description",
  "pickupAddress": "Westlands, Nairobi",
  "destination": "Nakuru Town"
}



### Update parcel status to IN_TRANSIT
PATCH http://localhost:3000/admin/parcels/318e33a4-7365-46bb-a800-c16bb2faee04/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNjRlMDhlZS1hMzgyLTRlOTEtYWYxZC1kYjVhYTJmNGZhNzIiLCJlbWFpbCI6ImpvbmF0aGFubXVsaW5nZW13YW5kaUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTI0NDczMTEsImV4cCI6MTc1MjUzMzcxMX0.yrCWtZX7ZqM6B7moRFItvRG02RgcALZDksWWZt3oj-s

{
  "status": "DELIVERED"
}

### Soft delete a parcel
DELETE http://localhost:3000/admin/parcels/REPLACE_PARCEL_ID
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNjRlMDhlZS1hMzgyLTRlOTEtYWYxZC1kYjVhYTJmNGZhNzIiLCJlbWFpbCI6ImpvbmF0aGFubXVsaW5nZW13YW5kaUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTIzNjAyNjksImV4cCI6MTc1MjQ0NjY2OX0.VxkgB9LMNUM9rxrkhtaFtOZrhgN63MV1mEUuxkMnHlE


### Get parcel stats
GET http://localhost:3000/admin/parcels/stats
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNjRlMDhlZS1hMzgyLTRlOTEtYWYxZC1kYjVhYTJmNGZhNzIiLCJlbWFpbCI6ImpvbmF0aGFubXVsaW5nZW13YW5kaUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTI0NDczMTEsImV4cCI6MTc1MjUzMzcxMX0.yrCWtZX7ZqM6B7moRFItvRG02RgcALZDksWWZt3oj-s

### Get parcel by id
GET http://localhost:3000/admin/parcels/a64a64c5-5324-456f-b223-e321e6aa0059
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNjRlMDhlZS1hMzgyLTRlOTEtYWYxZC1kYjVhYTJmNGZhNzIiLCJlbWFpbCI6ImpvbmF0aGFubXVsaW5nZW13YW5kaUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTI0NDczMTEsImV4cCI6MTc1MjUzMzcxMX0.yrCWtZX7ZqM6B7moRFItvRG02RgcALZDksWWZt3oj-s


### Get parcel trends
GET http://localhost:3000/admin/parcels/trends
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNjRlMDhlZS1hMzgyLTRlOTEtYWYxZC1kYjVhYTJmNGZhNzIiLCJlbWFpbCI6ImpvbmF0aGFubXVsaW5nZW13YW5kaUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTI0NDczMTEsImV4cCI6MTc1MjUzMzcxMX0.yrCWtZX7ZqM6B7moRFItvRG02RgcALZDksWWZt3oj-s


### assign parcel to driver
### Assign parcel to driver (driverId in body)
PATCH http://localhost:3000/admin/parcels/5671970b-0511-462a-aa22-5ea68d61406d/assign-driver
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNjRlMDhlZS1hMzgyLTRlOTEtYWYxZC1kYjVhYTJmNGZhNzIiLCJlbWFpbCI6ImpvbmF0aGFubXVsaW5nZW13YW5kaUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTM4MDY5MjMsImV4cCI6MTc1Mzg5MzMyM30.RO6uuXsIpxc0D4xwyoz46fI7Dha48zNwm6tGCmO3DMw

{
  "driverId": "71919c04-5634-4722-84e8-30db643fc444"
}
