### Add tracking entry:
POST http://localhost:3000/admin/parcels/799d16bd-851c-4c5f-8849-c9865463645f/tracking
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MTkxOWMwNC01NjM0LTQ3MjItODRlOC0zMGRiNjQzZmM0NDQiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpQGdtYWlsLmNvbSIsInJvbGUiOiJEUklWRVIiLCJpYXQiOjE3NTM4MDg5ODYsImV4cCI6MTc1Mzg5NTM4Nn0.9uEjTu-fzoRykpuICqkygfnqk79QMFnrHJaoDUjk2Hg


{
  "status": "IN_TRANSIT",
  "location": "Nairobi Hub",
  "note": "Left sorting facility"
}

### Get tracking for parcel:
GET http://localhost:3000/admin/parcels/43147f9d-d102-434a-9353-df2c271fa878/tracking
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNjRlMDhlZS1hMzgyLTRlOTEtYWYxZC1kYjVhYTJmNGZhNzIiLCJlbWFpbCI6ImpvbmF0aGFubXVsaW5nZW13YW5kaUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTI2ODU4MzUsImV4cCI6MTc1Mjc3MjIzNX0.S7woXJVF9WXFOYp_LhCU7pJaw6c_1g5LoNA0uijszkc


### Get all tracking entries:
GET http://localhost:3000/admin/parcels/tracking/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNjRlMDhlZS1hMzgyLTRlOTEtYWYxZC1kYjVhYTJmNGZhNzIiLCJlbWFpbCI6ImpvbmF0aGFubXVsaW5nZW13YW5kaUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTI2ODU4MzUsImV4cCI6MTc1Mjc3MjIzNX0.S7woXJVF9WXFOYp_LhCU7pJaw6c_1g5LoNA0uijszkc

